[package]
name = "lunabot-cu"
version = "0.1.0"
edition = "2024"
default-run = "lunabot"
build = "build.rs"


# The main executable of your application
[[bin]]
name = "lunabot"
path = "src/main.rs"

# A custom made log reader application for your application.
[[bin]]
name = "lunabot-logreader"
path = "src/logreader.rs"
required-features = ["logreader"]

[features]
production = [
    "cu-apriltag/hardware",
    "udev",
    "gstreamer",
    "gstreamer-app",
    "cu-gstreamer",
    "circular-buffer",
    "launcher",
    "tokio-serial",
    "vesc-translator",
    "mio",
    "cobs",
    "bytes",
    "quic",
    "iceoryx2",
    "iceoryx-types/production",
    "t265-rs",
]

logreader = ["dep:cu29-export"]
resim = ["dep:cu29-export", "cu-apriltag/resim", "iceoryx-types/resim"]
sim = ["cu-apriltag/sim", "mujoco-rs", "quic", "iceoryx-types/sim"]

[[bin]]
name = "lunabot-resim"
path = "src/resim.rs"
required-features = ["resim"]

[[bin]]
name = "lunabot-sim"
path = "src/sim.rs"
required-features = ["sim"]

[dependencies]

# copper
cu29.workspace = true
cu-bincode.workspace = true
cu29-helpers.workspace = true
cu29-export = { workspace = true, optional = true }
# cu_cursiveconsolemon.workspace = true
# cu-consolemon.workspace = true
cu-sensor-payloads.workspace = true
cu-spatial-payloads.workspace = true
cu29-runtime.workspace = true
cu-apriltag.workspace = true
crossbeam-channel.workspace = true
anyhow = "1"
serde.workspace = true
iceoryx2 = { workspace = true, optional = true }
# libc = "0.2.173"
# nix = { version = "0.30.1", features = ["time"] }
bytemuck.workspace = true
nalgebra.workspace = true
# kiss-icp-core = { path = "../kiss-icp-rs/core" }
# kiss-icp-ops = { path = "../kiss-icp-rs/ops" }
simple-icp = { git = "https://github.com/utahrobotics/simple-icp.git" }
rayon = "1.10"

crossbeam.workspace = true

rerun = { version = "0.27.2", features = ["sdk"], default-features = false }

# embedded
embedded_common = { path = "../embedded_common", features = ["std"] }

# RON deserialization at runtime
ron.workspace = true
serde-big-array.workspace = true

# misc
simple-motion = { path = "../misc/simple-motion" }
bitcode = "0.6.6"
tasker = { path = "../misc/tasker" }
iceoryx-types = { path = "../misc/iceoryx-types" }
launcher = { path = "../misc/launcher", optional = true }
vesc-translator = { path = "../misc/vesc-translator", optional = true }
kfilter = { git = "https://github.com/utahrobotics/kfilter.git" }
quic = { path = "../misc/quic", optional = true }
wgsl-pcl = { path = "../misc/wgsl-pcl" }

# common
common = { path = "../common" }

tokio-serial = { workspace = true, optional = true }
futures-util.workspace = true
tokio-util.workspace = true
cobs = { workspace = true, optional = true }
bytes = { version = "1.10.1", optional = true }
mio = { version = "1.0.4", optional = true }
bonsai-bt = { git = "https://github.com/utahrobotics/bonsai.git" }

# production hardware feature only
udev = { version = "0.9", features = ["mio10"], optional = true }
gstreamer = { version = "0.24.0", optional = true }
circular-buffer = { version = "1.1.0", optional = true }
gstreamer-app = { version = "0.24.0", optional = true }
cu-gstreamer = { workspace = true, optional = true }
colorous = "1.0.16"
t265-rs ={ git = "https://github.com/utahrobotics/t265-rs.git",optional = true }


# sim deps
mujoco-rs = { version = "2.2.2", features = [
    "cpp-viewer",
    "renderer",
], optional = true, default-features = false }
rand = "0.9.2"
ctrlc = "3.5.2"

[build-dependencies]
ron.workspace = true
serde.workspace = true
