[workspace]
resolver = "3"
members = [
    "misc/simple-motion",
    "misc/tasker",
    "misc/thalassic",
    "misc/gputter",
    "misc/iceoryx-types",
    "misc/launcher",
    "misc/vesc-translator",
    "common",
    "lunabot-cu",
    "embedded_common",
    "external-tasks/realsense",
    "lunabase-lib",
    "misc/quic",
]
exclude = ["misc/usb-reset"]
# Shared dependencies across workspace members
[workspace.dependencies]
cu29 = { git = "https://github.com/matthewashton-k/copper-rs.git", branch = "master", package = "cu29", features = [
    "log-level-info",
    "log-level-error",
] }
cu29-export = { git = "https://github.com/matthewashton-k/copper-rs.git", branch = "master", package = "cu29-export" }

bincode = { version = "2", features = ["derive", "serde"] }
cu29-helpers = { git = "https://github.com/matthewashton-k/copper-rs.git", branch = "master", package = "cu29-helpers" }
cu-apriltag = { git = "https://github.com/matthewashton-k/copper-rs.git", branch = "master", package = "cu-apriltag" }
# cu-consolemon = { git = "https://github.com/matthewashton-k/copper-rs.git", branch = "master", package = "cu-consolemon" }
cu-sensor-payloads = { git = "https://github.com/matthewashton-k/copper-rs.git", branch = "master", package = "cu-sensor-payloads" }
cu-spatial-payloads = { git = "https://github.com/matthewashton-k/copper-rs.git", branch = "master", package = "cu-spatial-payloads", features = [
    "nalgebra",
] }
cu29-runtime = { git = "https://github.com/matthewashton-k/copper-rs.git", branch = "master", package = "cu29-runtime" }
cu-gstreamer = { git = "https://github.com/matthewashton-k/copper-rs.git", branch = "master", package = "cu-gstreamer", features = [
    "gst",
] }
iceoryx2 = { version = "0.7.0" }
crossbeam = "0.8"
crossbeam-channel = "0.5"


toml = "0.9.5"
bitcode = "0.6.7"

nalgebra = { version = "0.34.0", features = [
    "serde-serialize",
    "convert-bytemuck",
] }

ron = { version = "0.11.0", features = ["indexmap"] }
fxhash = "0.2.1"
indexmap = "2.9.0"
tokio = { version = "1", features = ["full"] }
parking_lot = "0.12.2"
bytemuck = { version = "1", features = ["derive", "extern_crate_alloc"] }
anyhow = "1"
unfmt = "0.2.2"
serde = { version = "1", features = ["derive"] }

tokio-serial = "5.4.5"
tokio-util = "0.7.16"
futures-util = "0.3.31"
cobs = "0.5.0"

# members
common = { path = "common" }
# Workspace-level metadata
[workspace.metadata]
# You can add custom metadata here if needed
