[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck.workspace = true
bitcode.workspace = true
nalgebra.workspace = true
once_cell = "1.19"
crossbeam.workspace = true
embedded_common = { path = "../embedded_common" }
cu-bincode.workspace = true
serde.workspace = true
