[package]
name = "multiplexed-camera-viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.34.1", default-features = false, features = ["glow", "default_fonts", "wayland"] }
egui = "0.34.1"
egui_extras = {version = "0.34.1", features = ["default", "all_loaders"] }
ron = "0.12.1"
serde = { version = "1.0.228", features = ["derive"] }
ffmpeg-next = "8.1.0"
egui_tiles = "0.15.0"
