[package]
name = "iceoryx-types"
version = "0.1.0"
edition = "2021"

[dependencies]
iceoryx2 = "0.6.1"
bincode = { version = "=2.0.1", features = ["derive", "serde"] }
serde = { version = "1", features = ["derive"] }
nalgebra.workspace = true
